version: 1

steps:
  develop:
    prepare:
      - composer validate
      - composer install --no-progress --prefer-dist --no-dev --optimize-autoloader
    process:
      - vendor/bin/drupal build
    finalize:
      - vendor/bin/drupal cr all
