command:
  name: build
  description: 'Build site'
commands:
  # Install site
  - command: site:install
    options:
      force: true
    arguments:
      profile: standard
  # Install config_suite module
  - command: 'module:install'
    arguments:
      module:
        - config_suite
  # Import configurations
  - command: 'config:import'
  # Execute pending hook_updates
  - command: 'update:execute'
  # Rebuild caches
  - command: 'cache:rebuild'
    arguments:
        cache: all
